import { db } from "./db";
import { submissions } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  const [existingCount] = await db.select({ count: sql<number>`count(*)::int` }).from(submissions);
  
  if (existingCount.count > 0) {
    console.log(`Database already has ${existingCount.count} submissions, skipping seed.`);
    return;
  }

  console.log("Seeding database with sample data...");

  const sampleSubmissions = [
    {
      source: "web" as const,
      status: "aprobado" as const,
      nombreApellidos: "María García Fernández",
      telefono: "987654321",
      email: "maria.garcia@email.com",
      localidad: "Ponferrada",
      genero: "mujer" as const,
      edad: "entre_35_50" as const,
      relacionFinca: "propietario" as const,
      titularidadCompartida: "no" as const,
      agricultorTituloPrincipal: "si" as const,
      asociacionPertenece: "Asociación de Agricultores del Bierzo",
      referenciasCatastrales: "24118A00100045",
      superficieCategoria: "entre_1_5ha" as const,
      tipoFinca: ["agricola", "forestal"],
      usoSuelo: "cultivo_activo" as const,
      enProduccion: true,
      acceso: "bueno" as const,
      agua: "si" as const,
      pendiente: "baja" as const,
      pedregosidad: "media" as const,
      necesidades: ["mejora_productividad", "control_matorral"],
      objetivosModelo: ["produccion", "conservacion"],
      produccionPrincipal: ["castana", "fruticola"],
      gradoInteres: "alto" as const,
      nivelActuacion: "implantacion" as const,
      disponibilidad: ["reuniones_talleres", "visitas_tecnicas", "seguimiento"],
      relevoGeneracional: "si_familiares" as const,
      formacion: ["cultivo_castano", "sistemas_agroforestales"],
      colaboracion: "si_agrupacion" as const,
      minifundio: "si_asumible" as const,
      cesionTierras: "si_contrato" as const,
      gobernanzaComunidad: ["empleo_local", "recuperar_tierras"],
      consentimientoTratamiento: true,
      aceptoComunicaciones: true,
    },
    {
      source: "web" as const,
      status: "enviado" as const,
      nombreApellidos: "José Antonio López Martínez",
      telefono: "654123789",
      email: "joseantonio@email.com",
      localidad: "Cacabelos",
      genero: "hombre" as const,
      edad: "mas_50" as const,
      relacionFinca: "propietario" as const,
      titularidadCompartida: "si" as const,
      agricultorTituloPrincipal: "no_complementario" as const,
      referenciasCatastrales: "24029A00500123\n24029A00500124",
      superficieCategoria: "mas_5ha" as const,
      tipoFinca: ["mixta"],
      usoSuelo: "pasto" as const,
      enProduccion: true,
      acceso: "regular" as const,
      agua: "si" as const,
      pendiente: "media" as const,
      pedregosidad: "baja" as const,
      necesidades: ["prevencion_incendios", "mejora_suelo", "diversificacion_usos"],
      objetivosModelo: ["produccion", "reduccion_costes"],
      produccionPrincipal: ["pasto_ganadera", "lena"],
      gradoInteres: "alto" as const,
      nivelActuacion: "implantacion" as const,
      disponibilidad: ["visitas_tecnicas"],
      relevoGeneracional: "no_riesgo_abandono" as const,
      formacion: ["ganaderia_regenerativa", "tramitacion_ayudas"],
      colaboracion: "si_puntuales" as const,
      minifundio: "si_mucho" as const,
      cesionTierras: "si_municipio" as const,
      gobernanzaComunidad: ["formacion_capacitacion"],
      consentimientoTratamiento: true,
      aceptoComunicaciones: false,
    },
    {
      source: "web" as const,
      status: "enviado" as const,
      nombreApellidos: "Ana Belén Rodríguez Álvarez",
      telefono: "612345678",
      email: "anabelen.rodriguez@email.com",
      localidad: "Bembibre",
      genero: "mujer" as const,
      edad: "menos_35" as const,
      relacionFinca: "arrendatario" as const,
      agricultorTituloPrincipal: "si" as const,
      asociacionPertenece: "Jóvenes Agricultores",
      referenciasCatastrales: "24015A00200089",
      superficieCategoria: "menos_1ha" as const,
      tipoFinca: ["agricola"],
      usoSuelo: "cultivo_activo" as const,
      enProduccion: true,
      acceso: "bueno" as const,
      agua: "si" as const,
      pendiente: "baja" as const,
      pedregosidad: "baja" as const,
      necesidades: ["mejora_productividad", "diversificacion_usos"],
      objetivosModelo: ["produccion", "impacto_social"],
      produccionPrincipal: ["horticola"],
      gradoInteres: "alto" as const,
      nivelActuacion: "implantacion" as const,
      disponibilidad: ["reuniones_talleres", "visitas_tecnicas", "seguimiento"],
      relevoGeneracional: "si_familiares" as const,
      formacion: ["agricultura_regenerativa", "comercializacion"],
      colaboracion: "si_agrupacion" as const,
      minifundio: "no_adecuado" as const,
      cesionTierras: "no" as const,
      gobernanzaComunidad: ["empleo_local", "cooperativas_colectivas"],
      consentimientoTratamiento: true,
      aceptoComunicaciones: true,
    },
    {
      source: "web" as const,
      status: "borrador" as const,
      nombreApellidos: "Carlos Fernández Núñez",
      telefono: "698765432",
      localidad: "Carracedelo",
      genero: "hombre" as const,
      edad: "entre_35_50" as const,
      relacionFinca: "propietario" as const,
      titularidadCompartida: "no" as const,
      agricultorTituloPrincipal: "no_complementario" as const,
      referenciasCatastrales: "24033A00300056",
      superficieCategoria: "entre_1_5ha" as const,
      tipoFinca: ["forestal"],
      usoSuelo: "monte" as const,
      enProduccion: false,
      acceso: "malo" as const,
      agua: "no" as const,
      pendiente: "alta" as const,
      pedregosidad: "alta" as const,
      necesidades: ["control_matorral", "prevencion_incendios", "puesta_valor_abandonada"],
      gradoInteres: "medio" as const,
      nivelActuacion: "solo_diagnostico" as const,
      colaboracion: "no_se_asesoria" as const,
      minifundio: "si_mucho" as const,
      cesionTierras: "si_contrato" as const,
      consentimientoTratamiento: true,
    },
    {
      source: "web" as const,
      status: "aprobado" as const,
      nombreApellidos: "Pilar Sánchez Vega",
      telefono: "678901234",
      email: "pilar.sanchez@email.com",
      localidad: "Villafranca del Bierzo",
      genero: "mujer" as const,
      edad: "mas_50" as const,
      relacionFinca: "gestor" as const,
      agricultorTituloPrincipal: "si" as const,
      asociacionPertenece: "Cooperativa Agrícola del Bierzo",
      referenciasCatastrales: "24206A00400078\n24206A00400079\n24206A00400080",
      superficieCategoria: "mas_5ha" as const,
      tipoFinca: ["agricola", "mixta"],
      usoSuelo: "cultivo_activo" as const,
      enProduccion: true,
      acceso: "bueno" as const,
      agua: "si" as const,
      pendiente: "media" as const,
      pedregosidad: "media" as const,
      necesidades: ["mejora_productividad", "mejora_suelo"],
      objetivosModelo: ["produccion", "conservacion", "reduccion_costes"],
      produccionPrincipal: ["vid", "fruticola", "apicolas"],
      gradoInteres: "alto" as const,
      nivelActuacion: "implantacion" as const,
      disponibilidad: ["reuniones_talleres", "visitas_tecnicas", "seguimiento"],
      relevoGeneracional: "buscando" as const,
      formacion: ["sistemas_agroforestales", "legislacion_fiscalidad", "plantaciones_carbono"],
      colaboracion: "si_agrupacion" as const,
      minifundio: "si_asumible" as const,
      cesionTierras: "si_contrato" as const,
      gobernanzaComunidad: ["empleo_local", "recuperar_tierras", "turismo_rural"],
      observaciones: "Estoy muy interesada en participar en el proyecto. Tenemos experiencia en cultivos tradicionales y nos gustaría diversificar hacia modelos más sostenibles.",
      consentimientoTratamiento: true,
      aceptoComunicaciones: true,
    },
  ];

  await db.insert(submissions).values(sampleSubmissions);
  console.log(`Seeded ${sampleSubmissions.length} sample submissions.`);
}
